repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Optional: specify a revision like rev: 'v0.1.0'
    rev: 'v0.11.9' # Use a recent stable version
    hooks:
      - id: ruff
        name: ruff (lint)
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff (format)
        types_or: [python, pyi]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: []

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  # Pytest hook # This line and below needs to be indented
#  - repo: local
#    hooks:
#      - id: pytest
#        name: pytest
#        entry: pytest
#        language: system
#        types: [python]
#        pass_filenames: false
#        # Consider `stages: [commit]` if you only want to run on commit
        # and not with `pre-commit run --all-files` unless specified.
